# Generated by Django 5.1.1 on 2024-09-14 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('volume', models.CharField(max_length=20)),
                ('power', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rudder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=20)),
                ('mileage', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('photo', models.ImageField(upload_to='cars/')),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.bodytype')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.engine')),
                ('rudder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.rudder')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.transmission')),
            ],
        ),
    ]
