# Generated by Django 5.1.1 on 2024-09-23 15:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodytype',
            options={'ordering': ['type'], 'verbose_name_plural': 'Тип Кузова'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['name'], 'verbose_name_plural': 'Автомобиль'},
        ),
        migrations.AlterModelOptions(
            name='engine',
            options={'ordering': ['name'], 'verbose_name_plural': 'Двигатель'},
        ),
        migrations.AlterModelOptions(
            name='rudder',
            options={'ordering': ['type'], 'verbose_name_plural': 'Руль'},
        ),
        migrations.AlterModelOptions(
            name='transmission',
            options={'ordering': ['type'], 'verbose_name_plural': 'Коробка передач'},
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default='No description', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.bodytype', verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=40, verbose_name='Брэнд'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=20, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.engine', verbose_name='Двигатель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.CharField(max_length=40, verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(upload_to='cars/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='car',
            name='rudder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.rudder', verbose_name='Руль'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.transmission', verbose_name='Коробка передач'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='power',
            field=models.CharField(max_length=20, verbose_name='Мощность'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='volume',
            field=models.CharField(max_length=20, verbose_name='Объем'),
        ),
        migrations.CreateModel(
            name='TestDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер Телефона')),
                ('preferred_date', models.DateField(verbose_name='Дата')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('approved', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано в:')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.car', verbose_name='Модель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Тест Драйвы',
            },
        ),
    ]
