# Generated by Django 5.1.1 on 2024-09-24 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_alter_bodytype_options_alter_car_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarLoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер Телефона')),
                ('loan_term', models.IntegerField(verbose_name='Срок кредита в месяцах')),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Годовой доход')),
                ('approved', models.CharField(choices=[('pending', 'Ожидание'), ('approved', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=10, verbose_name='Статус')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.car', verbose_name='Модель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Автокредит',
            },
        ),
    ]
