# Generated by Django 5.1.1 on 2024-09-25 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_carloanapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('full', 'Полное покрытие'), ('partial', 'Частичное покрытие'), ('liability', 'Ответственность перед третьими лицами')], max_length=10, verbose_name='Тип полиса')),
                ('start_date', models.DateField(verbose_name='Начало срока')),
                ('end_date', models.DateField(verbose_name='Конец срока')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('approved', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=10, verbose_name='Статус')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.car', verbose_name='Модель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Страховщик')),
            ],
        ),
    ]
