# Generated by Django 5.1.1 on 2024-09-26 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_insurancepolicy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurancepolicy',
            options={'verbose_name_plural': 'Страховки'},
        ),
        migrations.CreateModel(
            name='PaymentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.CharField(max_length=20, verbose_name='Паспорт')),
                ('driving_license', models.CharField(max_length=20, verbose_name='Водительская права')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('bank', 'Банковский счет')], max_length=20, verbose_name='Тип оплаты')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.car', verbose_name='Модель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Оплата',
            },
        ),
    ]
