# Generated by Django 5.1.1 on 2024-09-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_alter_insurancepolicy_options_paymentform'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentform',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID платежа Stripe'),
        ),
    ]
