# Generated by Django 5.1.1 on 2024-10-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_paymentform_stripe_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentform',
            name='card_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='paymentform',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='paymentform',
            name='card_validity_period',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
